apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  type: NodePort
  ports:
    - nodePort: 31317
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: django